url: "https://www.bayis.co.uk"
baseurl: ""

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "library"
      type: "pages"
    values:
      layout: article

permalink: /library/:title.html
