url: "https://www.bayis.co.uk"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

collections:
  checklists:
    output: true
    permalink: /checklists/:name.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /library/:title.html
  - scope:
      path: "library"
      type: "pages"
    values:
      layout: article
  - scope:
      path: ""
      type: "checklists"
    values:
      layout: checklist

author:
  name: "Edward Grundy"
  url: "https://www.bayis.co.uk/about#edward-grundy"
